project:
  type: website
  output-dir: docs
  resources:
    - 73_Nonparametric_Greedy_Equiva-8.pdf

website:
  title: "Mateusz Gajewski"
  page-navigation: false
  search: false

  navbar:
    background: "#F0F0F0"
    foreground: "#333333"
    title: "Mateusz Gajewski"
    right:
      - text: Research
        href: research.qmd

  page-footer:
    background: "#F0F0F0"
    foreground: "#333333"
    center: "Mateusz Gajewski &copy; 2026"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
